### PR TITLE
5.0 updates

### PR DESCRIPTION
**Pull request by ericras**

### CODE REVIEW

**Comment by ericras** [comment]
This is the sort of one where I wouldn't squash

**Comment by jsturek** [comment]
Agreed. Reviewing...

**Comment by jsturek** [comment]
- [ ] Got this warning after a news article save: `Warning: preg_replace(): Compilation failed: invalid range in character class at offset 4 in /Library/WebServer/Documents/UNL_ENews/src/UNL/ENews/Controller.php on line 291`.  Probably a PHP 7.2 version but should try to fix.

**Comment by jsturek** [comment]
Looks good other than issue preg_replace issue.

**Pull request merged**
